<main class="greeting">
    <div class="greeting_page">
        <p>Добавьте необходимые данные о себе</p>
    </div>
    <div class="greeting_registration">
        <form method="post" name="registration_info" action="#" class="greeting_registration_form">
            <br>Я из<br>
            <select class="greeting_registration_input" required>
                <option value="AF">AFGHANISTAN</option>
                <option value="AL">ALBANIA</option>
                <option value="AD">ANDORRA</option>
                <option value="AO">ANGOLA</option>
                <option value="AQ">ANTARCTICA</option>
                <option value="AR">ARGENTINA</option>
                <option value="AM">ARMENIA</option>
                <option value="AU">AUSTRALIA</option>
                <option value="AT">AUSTRIA</option>
                <option value="AZ">AZERBAIJAN</option>
                <option value="BS">BAHAMAS</option>
                <option value="BY">BELARUS</option>
                <option value="BE">BELGIUM</option>
                <option value="BA">BOSNIA AND HERZEGOWINA</option>
                <option value="BR">BRAZIL</option>
                <option value="BG">BULGARIA</option>
                <option value="CA">CANADA</option>
                <option value="CL">CHILE</option>
                <option value="CN">CHINA</option>
                <option value="CU">CUBA</option>
                <option value="CY">CYPRUS</option>
                <option value="CZ">CZECH REPUBLIC</option>
                <option value="DK">DENMARK</option>
                <option value="DO">DOMINICAN REPUBLIC</option>
                <option value="EG">EGYPT</option>
                <option value="EE">ESTONIA</option>
                <option value="FI">FINLAND</option>
                <option value="FR">FRANCE</option>
                <option value="GE">GEORGIA</option>
                <option value="DE">GERMANY</option>
                <option value="GR">GREECE</option>
                <option value="GL">GREENLAND</option>
                <option value="HK">HONG KONG</option>
                <option value="HU">HUNGARY</option>
                <option value="IS">ICELAND</option>
                <option value="IN">INDIA</option>
                <option value="ID">INDONESIA</option>
                <option value="IQ">IRAQ</option>
                <option value="IE">IRELAND</option>
                <option value="IL">ISRAEL</option>
                <option value="IT">ITALY</option>
                <option value="JM">JAMAICA</option>
                <option value="JP">JAPAN</option>
                <option value="KZ">KAZAKHSTAN</option>
                <option value="KG">KYRGYZSTAN</option>
                <option value="LV">LATVIA</option>
                <option value="LT">LITHUANIA</option>
                <option value="LU">LUXEMBOURG</option>
                <option value="MT">MALTA</option>
                <option value="MX">MEXICO</option>
                <option value="MC">MONACO</option>
                <option value="MN">MONGOLIA</option>
                <option value="NL">NETHERLANDS</option>
                <option value="NZ">NEW ZEALAND</option>
                <option value="NO">NORWAY</option>
                <option value="PL">POLAND</option>
                <option value="PT">PORTUGAL</option>
                <option value="RO">ROMANIA</option>
                <option value="RU">RUSSIAN FEDERATION</option>
                <option value="CS">SERBIA AND MONTENEGRO</option>
                <option value="SK">SLOVAKIA</option>
                <option value="SI">SLOVENIA</option>
                <option value="ZA">SOUTH AFRICA</option>
                <option value="ES">SPAIN</option>
                <option value="LK">SRI LANKA</option>
                <option value="SE">SWEDEN</option>
                <option value="CH">SWITZERLAND</option>
                <option value="TW">TAIWAN</option>
                <option value="TJ">TAJIKISTAN</option>
                <option value="TH">THAILAND</option>
                <option value="TR">TURKEY</option>
                <option value="TM">TURKMENISTAN</option>
                <option selected value="UA">UKRAINE</option>
                <option value="AE">UNITED ARAB EMIRATES</option>
                <option value="GB">UNITED KINGDOM</option>
                <option value="US">UNITED STATES</option>
                <option value="UZ">UZBEKISTAN</option>
                <option value="VN">VIET NAM</option>
            </select>
            <br>Сейчас работаю в<br>
            <select class="greeting_registration_input" required>
                <option value="AF">AFGHANISTAN</option>
                <option value="AL">ALBANIA</option>
                <option value="AD">ANDORRA</option>
                <option value="AO">ANGOLA</option>
                <option value="AQ">ANTARCTICA</option>
                <option value="AR">ARGENTINA</option>
                <option value="AM">ARMENIA</option>
                <option value="AU">AUSTRALIA</option>
                <option value="AT">AUSTRIA</option>
                <option value="AZ">AZERBAIJAN</option>
                <option value="BS">BAHAMAS</option>
                <option value="BY">BELARUS</option>
                <option value="BE">BELGIUM</option>
                <option value="BA">BOSNIA AND HERZEGOWINA</option>
                <option value="BR">BRAZIL</option>
                <option value="BG">BULGARIA</option>
                <option value="CA">CANADA</option>
                <option value="CL">CHILE</option>
                <option value="CN">CHINA</option>
                <option value="CU">CUBA</option>
                <option value="CY">CYPRUS</option>
                <option value="CZ">CZECH REPUBLIC</option>
                <option value="DK">DENMARK</option>
                <option value="DO">DOMINICAN REPUBLIC</option>
                <option value="EG">EGYPT</option>
                <option value="EE">ESTONIA</option>
                <option value="FI">FINLAND</option>
                <option value="FR">FRANCE</option>
                <option value="GE">GEORGIA</option>
                <option value="DE">GERMANY</option>
                <option value="GR">GREECE</option>
                <option value="GL">GREENLAND</option>
                <option value="HK">HONG KONG</option>
                <option value="HU">HUNGARY</option>
                <option value="IS">ICELAND</option>
                <option value="IN">INDIA</option>
                <option value="ID">INDONESIA</option>
                <option value="IQ">IRAQ</option>
                <option value="IE">IRELAND</option>
                <option value="IL">ISRAEL</option>
                <option value="IT">ITALY</option>
                <option value="JM">JAMAICA</option>
                <option value="JP">JAPAN</option>
                <option value="KZ">KAZAKHSTAN</option>
                <option value="KG">KYRGYZSTAN</option>
                <option value="LV">LATVIA</option>
                <option value="LT">LITHUANIA</option>
                <option value="LU">LUXEMBOURG</option>
                <option value="MT">MALTA</option>
                <option value="MX">MEXICO</option>
                <option value="MC">MONACO</option>
                <option value="MN">MONGOLIA</option>
                <option value="NL">NETHERLANDS</option>
                <option value="NZ">NEW ZEALAND</option>
                <option value="NO">NORWAY</option>
                <option selected value="PL">POLAND</option>
                <option value="PT">PORTUGAL</option>
                <option value="RO">ROMANIA</option>
                <option value="RU">RUSSIAN FEDERATION</option>
                <option value="CS">SERBIA AND MONTENEGRO</option>
                <option value="SK">SLOVAKIA</option>
                <option value="SI">SLOVENIA</option>
                <option value="ZA">SOUTH AFRICA</option>
                <option value="ES">SPAIN</option>
                <option value="LK">SRI LANKA</option>
                <option value="SE">SWEDEN</option>
                <option value="CH">SWITZERLAND</option>
                <option value="TW">TAIWAN</option>
                <option value="TJ">TAJIKISTAN</option>
                <option value="TH">THAILAND</option>
                <option value="TR">TURKEY</option>
                <option value="TM">TURKMENISTAN</option>
                <option value="UA">UKRAINE</option>
                <option value="AE">UNITED ARAB EMIRATES</option>
                <option value="GB">UNITED KINGDOM</option>
                <option value="US">UNITED STATES</option>
                <option value="UZ">UZBEKISTAN</option>
                <option value="VN">VIET NAM</option>
            </select>
            <br>
            <br>На должности<br>
            <select class="greeting_registration_input" required>
                <option value="">Агент коммерческий</option>
                <option value="">Агент страховой</option>
                <option value="">Адвокат</option>
                <option value="">Администратор</option>
                <option value="">Арт-директор</option>
                <option value="">Архитектор</option>
                <option value="">Аудитор</option>
                <option value="">Бизнес-консультант</option>
                <option value="">Бренд-менеджер</option>
                <option value="">Брокер</option>
                <option value="">Бухгалтер</option>
                <option value="">Бармен</option>
                <option value="">Бетонщик</option>
                <option value="">Библиотекарь</option>
                <option value="">Бизнес-консультант</option>
                <option value="">Бортинженер</option>
                <option value="">Бортпроводник</option>
                <option value="">Ботаник</option>
                <option value="">Бренд-менеджер</option>
                <option value="">Бригадир железнодорожного пути</option>
                <option value="">Бригадир поезда</option>
                <option value="">Бухгалтер-ревизор</option>
                <option value="">Верстальщик</option>
                <option value="">Веб-дизайнер</option>
                <option value="">Веб-программист</option>
                <option value="">Ветеринарный врач</option>
                <option value="">Визажист</option>
                <option value="">Водтель автомобиля</option>
                <option value="">Водитель такси</option>
                <option value="">Воспитатель детских дошкольных учреждений</option>
                <option value="">Врач инфекционист</option>
                <option value="">Главный бухгалтер</option>
                <option value="">Горнорабочий подземный</option>
                <option value="">Главный инженер</option>
                <option value="">Главный механик</option>
                <option value="">Главный программист</option>
                <option value="">Девелопер</option>
                <option selected value="">Дизайнер</option>
                <option value="">Дилер</option>
                <option value="">Диктор</option>
                <option value="">Диспетчер</option>
                <option value="">Дистрибьютор</option>
                <option value="">Журналист</option>
                <option value="">Закройщик</option>
                <option value="">Заведующий складом</option>
                <option value="">Зубной техник</option>
                <option value="">Инженер-программист</option>
                <option value="">Инкассатор</option>
                <option value="">Копирайтер</option>
                <option value="">Каменщик, печник</option>
                <option value="">Кондитер</option>
                <option value="">Кассир</option>
                <option value="">Косметолог</option>
                <option value="">Логистик</option>
                <option value="">Лингвист</option>
                <option value="">Маляр</option>
                <option value="">Манекенщица</option>
                <option value="">Маникюрша</option>
                <option value="">Маркетолог</option>
                <option value="">Маркшейдер</option>
                <option value="">Массажист</option>
                <option value="">Мастер общестроительных работ</option>
                <option value="">Мастер отделочных строительных работ</option>
                <option value="">Мастер столярно-плотничных и паркетных работ</option>
                <option value="">Математик</option>
                <option value="">Машинист (кочегар) котельной</option>
                <option value="">Машинист автомобильного крана</option>
                <option value="">Машинист автопогрузчика</option>
                <option value="">Машинист башенного крана</option>
                <option value="">Машинист бульдозера</option>
                <option value="">Машинист горно-вымоечных машин</option>
                <option value="">Машинист дорожных и строительных машин</option>
                <option value="">Машинист компрессорных установок</option>
                <option value="">Машинист крана металлургического производства</option>
                <option value="">Машинист мостового и башенного крана</option>
                <option value="">Машинист тепловоза</option>
                <option value="">Машинист тесторазделочных машин</option>
                <option value="">Машинист электровоза на горных выработках</option>
                <option value="">Менеджер</option>
                <option value="">Менеджер по туризму</option>
                <option value="">Менеджер торгового зала</option>
                <option value="">Мерчендайзер</option>
                <option value="">Монтажник связи</option>
                <option value="">Монтажник систем вентиляции</option>
                <option value="">Монтажник стальных и железобетонных конструкций</option>
                <option value="">Монтажник технологического оборудования</option>
                <option value="">Нотариус</option>
                <option value="">Оператор-кузнец</option>
                <option value="">Официант</option>
                <option value="">Облицовщик-плиточник</option>
                <option value="">Оператор поста управления</option>
                <option value="">Оператор ПК</option>
                <option value="">Отделочник</option>
                <option value="">Офис-менеджер</option>
                <option value="">Охотник</option>
                <option value="">Оценщик</option>
                <option value="">Провизор</option>
                <option value="">Промоутер</option>
                <option value="">Помощник машиниста локомотива, тепловоза</option>
                <option value="">Плавильщик ферросплавов</option>
                <option value="">Печатник</option>
                <option value="">Портной</option>
                <option value="">Пекарь</option>
                <option value="">Повар</option>
                <option value="">Повар-кондитер</option>
                <option value="">Продавец</option>
                <option value="">Проходчик</option>
                <option value="">Плотник</option>
                <option value="">Парикмахер</option>
                <option value="">Переводчик</option>
                <option value="">Программист</option>
                <option value="">Продавец-консультант</option>
                <option value="">Прораб</option>
                <option value="">Психолог</option>
                <option value="">Слесарь-ремонтник</option>
                <option value="">Столяр строительный</option>
                <option value="">Станочник широкого профиля</option>
                <option value="">Страховой агент</option>
                <option value="">Секретарь-референт</option>
                <option value="">Секретарь-машинистка</option>
                <option value="">Секретарь-ресепшионист</option>
                <option value="">Системный администратор</option>
                <option value="">Сиделка</option>
                <option value="">Социолог</option>
                <option value="">Супервайзер</option>
                <option value="">Торговый представитель</option>
                <option value="">Токарь-универсал</option>
                <option value="">Токарь</option>
                <option value="">Тракторист-машинист сельскохозяйственного производства</option>
                <option value="">Телохранитель</option>
                <option value="">Тестер</option>
                <option value="">Учитель</option>
                <option value="">Фотограф</option>
                <option value="">Штукатур, маляр</option>
                <option value="">Швея</option>
                <option value="">Шеф-повар</option>
                <option value="">Экономист</option>
                <option value="">Электрик</option>
                <option value="">Юрист</option>
            </select>
            <br>Зарабатываю<br>
            <select class="greeting_registration_input" required>
                <option value="">...100$</option>
                <option value="">100-300$</option>
                <option value="">300-500$</option>
                <option value="">500-1000$</option>
                <option selected value="">1000-1500$</option>
                <option value="">1500-2000$</option>
                <option value="">2000-3000$</option>
                <option value="">3000-5000$</option>
                <option value="">5000-...$</option>
            </select>
            <br><br>
            Добавьте свое фото
            <input type="file" accept="image/*" name="user_foto"><br>
            <br>
            <p>О себе</p>
            <textarea class="greeting_registration_input" name="about" cols="40" rows="7"></textarea>
            <br><br>
            <p><input type="submit" value="Создать аккаунт" class="btn_submit"></p>
        </form>
    </div>
</main>